/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package question2_the;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import question2_the.iEstateAgent.Data;
/**
 *
 * @author lab_services_student
 */
public class Question2 extends javax.swing.JFrame {
  private JTextField txtname = new JTextField(20);
    private JTextField txtprice = new JTextField(20);
    private JTextField txtperc = new JTextField(20);
    private JComboBox<String> cmblocation = new JComboBox<>();
    private JTextArea displayArea = new JTextArea(10, 30);
    private JButton btngenerate = new JButton("Generate");

    private Question2 estateAgent = new Question2();

    public Question2() {
        setTitle("Estate Agent Commission Calculator");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Add items to locationComboBox
        cmblocation.addItem("Durban");
        cmblocation.addItem("Cape Town");
        cmblocation.addItem("Pretoria");

        // Add action listener to the calculate button
       btngenerate.addActionListener((ActionEvent e) -> {
           String agentName = txtname.getText();
           String propertyPrice = txtprice.getText();
           String commissionPercentage = txtperc.getText();
           String location = (String) cmblocation.getSelectedItem();
           
           // Validate the data and calculate the commission
           Data dataToValidate = new Data(agentName, propertyPrice, commissionPercentage, location);
           if (estateAgent.validateData(dataToValidate)) {
               double commission = estateAgent.calculateCommission(propertyPrice, commissionPercentage);
               displayArea.setText("Agent Name: " + agentName + "\n");
               displayArea.append("Property Price: " + propertyPrice + "\n");
               displayArea.append("Commission Percentage: " + commissionPercentage + "%\n");
               displayArea.append("Location: " + location + "\n");
               displayArea.append("Commission: " + commission + "\n");
           } else {
               displayArea.setText("Invalid data. Please check the input.");
           }
        });

        // Create a panel to hold the components
        JPanel panel = new JPanel();
        panel.add(new JLabel("Agent Name:"));
        panel.add(txtname);
        panel.add(new JLabel("Property Price:"));
        panel.add(txtprice);
        panel.add(new JLabel("Commission Percentage:"));
        panel.add(txtperc);
        panel.add(new JLabel("Location:"));
        panel.add(cmblocation);
        panel.add(btngenerate);

        // Add the panel and display area to the frame
        add(panel, "North");
        add(new JScrollPane(displayArea), "Center");
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new Question2().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllocation = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        commperc = new javax.swing.JLabel();
        lblreport = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportarea = new javax.swing.JTextArea();
        txtperc = new javax.swing.JTextField();
        cmblocation = new javax.swing.JComboBox<>();
        btngenerate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENT LOCATION");

        lbllocation.setText("AGENT LOCATION :");

        lblname.setText("ESTATE AGENT NAME :");

        lblprice.setText("PROPERTY PRICE :");

        commperc.setText("COMMISSION PERCENTAGE :");

        lblreport.setText("ESTATE AGENT REPORT ");

        reportarea.setColumns(20);
        reportarea.setRows(5);
        jScrollPane1.setViewportView(reportarea);

        cmblocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Pretoria" }));

        btngenerate.setText("Generate");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(commperc)
                            .addComponent(lblprice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllocation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblreport, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname)
                                    .addComponent(cmblocation, 0, 106, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtperc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btngenerate, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllocation)
                    .addComponent(cmblocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commperc)
                    .addComponent(txtperc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreport)
                    .addComponent(btngenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerate;
    private javax.swing.JComboBox<String> cmblocation;
    private javax.swing.JLabel commperc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblreport;
    private javax.swing.JTextArea reportarea;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtperc;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
